spring.application.name: "Demo"

logging:
  console:
    preset: spring
  file:
    preset: json
    path: ${java.io.tmpdir}
  pattern:
    dateformat:

  #  config: classpath:logback-docker.xml
  level:
    app: trace
    com.bkahlert.kommons.demo.DemoSpringApplication: debug

spring.banner.location: classpath:banner.txt
