name: Build and test

on:
  push:
    branches: ['master']
    tags: ['v*']
    paths-ignore: ['**.md']
  pull_request:
    branches: ['master']
    tags: ['dependencies']
    paths-ignore: ['**.md']

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Build
        uses: gradle/gradle-build-action@v2.1.0
        with:
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          arguments: build

      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: |
            build/dokka
            build/libs
            build/publications
            build/reports
            build/test-results
