name: build

on:
  push:
    branches: ['master']
    tags: ['v*']
    paths-ignore: ['**.md']
  pull_request:
    branches: ['master']
    tags: ['dependencies']
    paths-ignore: ['**.md']
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: 'master'
      additional-gradle-opts:
        description: "Additional Gradle options to set"
        required: false
        default: '--info --tests "com.bkahlert.kommons.logging.*"'

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=false -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Dfile.encoding=UTF-8 -Xmx3g -XX:MaxMetaspaceSize=756m -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError" ${{ github.event.inputs.additional-gradle-opts }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: jvm
            java-version: 8
          - os: ubuntu-latest
            target: jvm
            java-version: 11
          - os: ubuntu-latest
            target: jvm
            java-version: 17
          - os: macos-latest
            target: jvm
            java-version: 8
          - os: windows-latest
            target: jvm
            java-version: 8
          - os: windows-latest
            target: jvm
            java-version: 11
          - os: windows-latest
            target: jvm
            java-version: 17

          - os: ubuntu-latest
            target: js
            java-version: 8

          - os: ubuntu-latest
            target: linuxX64
            java-version: 8

          - os: windows-latest
            target: mingwX64
            java-version: 8

          - os: macos-latest
            target: macosX64
            java-version: 8


    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: adopt

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.target }}Test -Pkotlin.tests.individualTaskReports=true

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-reports--os-${{ matrix.os }}--target-${{ matrix.target }}--java-${{ matrix.java-version }}
          if-no-files-found: error
          path: ./**/build/test-results/**/*.xml

      - uses: actions/upload-artifact@v3
        with:
          name: kommons--os-${{ matrix.os }}--target-${{ matrix.target }}--java-${{ matrix.java-version }}
          if-no-files-found: error
          path: |
            ./**/build/dokka
            ./**/build/libs
            ./**/build/publications
            ./**/build/reports
            ./**/build/test-results
