name: Publish package to the Maven Central and GitHub Packages

on:
  release:
    types: ['published']
# TODO new pipeline that triggers on new tag, see RELEASING.md
#  push:
#    branches: ['master']
#    tags: ['v*']
#    paths-ignore: ['**.md']
#  pull_request:
#    branches: ['master']
#    tags: ['dependencies']
#    paths-ignore: ['**.md']

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Publish
        uses: gradle/gradle-build-action@v2.1.5
        with:
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          arguments: -Prelease.useLastTag=true final publish
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
