name: test-report

on:
  workflow_run:
    workflows: ['build', 'build-custom']
    types: ['completed']

permissions:
  contents: write

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: /^test-reports(?:--(.*$))?/
          name: Test reports $1
          path: '**/*.xml'
          reporter: java-junit
